### ISSUE TITLE
Validate cell names - should not have underscore character

### ISSUE THREAD

**Issue by hjensas** [openstack-k8s-operators/nova-operator#573]
Using underscore in cell name fails because we concatenate them for resource names and this is not supported for k8s resources. Let's add a validation for this in the webhook so that we can raise this issue to the user early.

For example below does not work because `baremetal_cell0` has an underscore in the name.
```yaml
    cellTemplates:
      cell0:
        [ ... ]
      baremetal_cell0:
        [ ... ]
```
